FROM python:3.6

#ADD . /src

#RUN cd /src; python setup.py install

#ENTRYPOINT ["/bin/bash"]

# Install packages required for the tests
COPY test-requirements.txt /tmp/test-requirements.txt
RUN pip install --no-cache-dir -r /tmp/test-requirements.txt