__all__ = list(
    map(
        str,
        [
            'connection',
            'activation',
            'directoryservice',
            'enum',
            'login',
            'whoami',
            'query',
            'logs',
            'portals',
            'remote',
            'servers',
            'devices',
            'session',
            'users',
            'cloudfs',
            'zones',
            'files',
            'decorator'
            ]
    )
)
