---
sessions:
  management:
    allow_unsafe: true
    ssl: true
    timeout:
      sock_connect: 30
      sock_read: 60
    edge:
      services:
        ssl: prompt
  ctera_direct:
    api:
      ssl: true
      timeout:
        sock_connect: 5
        sock_read: 10
    storage:
      ssl: true
      timeout:
        sock_connect: 5
        sock_read: 10
    streamer:
      max_workers: 20
  metadata_connector:
    allow_unsafe: true
    ssl: true
    timeout:
      sock_connect: 5
      sock_read: 10
logging:
  format: '%(asctime)s,%(msecs)3d %(levelname)7s [%(filename)s:%(lineno)d] [%(funcName)s] - %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'
  loggers:
    - name: common
      level: info
    - name: core
      level: info
    - name: edge
      level: info
    - name: metadata.connector
      level: info
    - name: filesystem
      level: error
    - name: direct
      level: error
    - name: crypto
      level: error
    - name: http
      level: error
    - name: http.trace
      level: error
downloads:
  location: ~/Downloads