---
sessions:
  management:
    allow_unsafe: true
    ssl: true
    edge:
      services:
        ssl: prompt
logging:
  format: '%(asctime)s,%(msecs)3d %(levelname)7s [%(filename)s:%(lineno)d] [%(funcName)s] - %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'
  loggers:
    - name: cterasdk.common
      level: info
    - name: cterasdk.core
      level: info
    - name: cterasdk.edge
      level: info
    - name: cterasdk.metadata.connector
      level: info
    - name: cterasdk.filesystem
      level: error
    - name: cterasdk.crypto
      level: error
    - name: cterasdk.http
      level: error
    - name: cterasdk.http.trace
      level: error
downloads:
  location: ~/Downloads