---
default_cookie_jar: &cookie_jar
  cookie_jar:
    unsafe: true

default_connector: &connector
  connector:
    ssl: true

default_timeout: &timeout
  timeout:
    sock_connect: 5
    sock_read: 10

default_settings: &default_settings
  settings:
    <<: *cookie_jar
    <<: *connector
    <<: *timeout

# CTERA Portal synchronous and asynchronous client configuration.
core:
  syn:
    settings:
      <<: *cookie_jar
      <<: *connector
      timeout:
        sock_connect: 30
        sock_read: 60
  asyn:
    <<: *default_settings

# CTERA Edge Filer synchronous client configuration.
edge:
  syn:
    settings:
      <<: *cookie_jar
      <<: *connector
      timeout:
        sock_connect: 30
        sock_read: 60
    services:
      ssl: prompt
  asyn:
    <<: *default_settings

# CTERA Drive synchronous client configuration.
drive:
  syn:
    <<: *default_settings

# CTERA asynchronous Direct IO client configuration.
io:
  direct:
    api:
      <<: *default_settings
    storage:
      <<: *default_settings
    streamer:
      max_workers: 20
  downloads: ~/Downloads

audit:
  enabled: false
  filename: ~